"""Scheduled automations (AIOS policy layer).

Turns "run this prompt every day at 8am" into a recurring job. This module owns
the **AIOS-neutral** parts: name validation, the wrapper that runs ``aios ask``,
and the automation index. It knows nothing about systemd — the actual OS
registration is delegated to an injected :class:`ServiceManager`
(``aiosd.platform.services``). That keeps the init/service system swappable
(Constitution §I; matrix rows #11/#12).

Automations run **plain ``aios ask``** — no tools — so a schedule can never
perform a mutating action unattended.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import time

from .platform.services import ScheduledJob

_NAME_RE = re.compile(r"[A-Za-z0-9_-]+")


class ScheduleError(ValueError):
    pass


def wrapper_script(aios_bin: str, prompt: str, log_path: str) -> str:
    """The command an automation runs: a plain `aios ask`, output appended to a log."""
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by `aios schedule` — runs an AIOS automation.\n"
        f"echo \"=== $(date) ===\" >> {shlex.quote(log_path)}\n"
        f"{shlex.quote(aios_bin)} ask {shlex.quote(prompt)} >> {shlex.quote(log_path)} 2>&1\n"
    )


class Scheduler:
    def __init__(self, service_manager, data_dir: str, aios_bin: str = "aios"):
        self.svc = service_manager
        self.auto_dir = os.path.join(data_dir, "automations")
        self.index_path = os.path.join(self.auto_dir, "index.json")
        self.aios_bin = aios_bin

    @property
    def available(self) -> bool:
        return self.svc.available

    # -- index helpers ----------------------------------------------------
    def _load_index(self) -> dict:
        if not os.path.exists(self.index_path):
            return {}
        try:
            with open(self.index_path, encoding="utf-8") as fh:
                return json.load(fh)
        except (OSError, ValueError):
            return {}

    def _save_index(self, index: dict) -> None:
        os.makedirs(self.auto_dir, exist_ok=True)
        with open(self.index_path, "w", encoding="utf-8") as fh:
            json.dump(index, fh, indent=2)

    # -- operations -------------------------------------------------------
    def add(self, name: str, when: str, prompt: str) -> dict:
        if not _NAME_RE.fullmatch(name):
            raise ScheduleError("name must be letters, digits, '-' or '_'")
        if not prompt.strip():
            raise ScheduleError("prompt is required")

        os.makedirs(self.auto_dir, exist_ok=True)
        log_path = os.path.join(self.auto_dir, f"{name}.log")
        wrapper_path = os.path.join(self.auto_dir, f"{name}.sh")
        with open(wrapper_path, "w", encoding="utf-8") as fh:
            fh.write(wrapper_script(self.aios_bin, prompt, log_path))
        os.chmod(wrapper_path, 0o755)

        result = self.svc.schedule(ScheduledJob(
            name=name, when=when, command=wrapper_path,
            description=f"AIOS automation: {name}",
        ))

        record = {"name": name, "when": when,
                  "calendar": result.get("calendar", when),
                  "backend": result.get("backend", "unknown"),
                  "prompt": prompt, "log": log_path, "created_at": time.time()}
        index = self._load_index()
        index[name] = record
        self._save_index(index)
        return record

    def list(self) -> list:
        return sorted(self._load_index().values(), key=lambda r: r.get("name", ""))

    def remove(self, name: str) -> bool:
        index = self._load_index()
        if name not in index:
            return False
        self.svc.unschedule(name)
        try:
            os.remove(os.path.join(self.auto_dir, f"{name}.sh"))
        except OSError:
            pass
        del index[name]
        self._save_index(index)
        return True
