"""Scheduled automations via systemd user timers.

Turn "run this prompt every day at 8am" into a systemd user service + timer that
runs ``aios ask`` on schedule and appends the answer to a log. Pure unit-text
generators plus a ``Scheduler`` that manages the files (and, when available,
``systemctl --user``).

Automations run **plain `aios ask`** — no tools — so a timer can never perform a
mutating action unattended.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
import time

_WEEKDAYS = {"mon": "Mon", "tue": "Tue", "wed": "Wed", "thu": "Thu",
             "fri": "Fri", "sat": "Sat", "sun": "Sun"}
_NAME_RE = re.compile(r"[A-Za-z0-9_-]+")


class ScheduleError(ValueError):
    pass


def _is_time(s: str) -> bool:
    hh, sep, mm = s.partition(":")
    return bool(sep) and hh.isdigit() and mm.isdigit()


def _norm_time(s: str) -> str:
    hh, mm = s.split(":")[:2]
    return f"{int(hh):02d}:{int(mm):02d}:00"


def to_oncalendar(when: str) -> str:
    """Map a friendly schedule to a systemd OnCalendar string (or pass it through)."""
    text = when.strip()
    low = text.lower()
    if low in ("hourly", "daily", "weekly", "monthly", "yearly"):
        return low
    parts = low.split()
    if len(parts) == 2 and parts[0][:3] in _WEEKDAYS and _is_time(parts[1]):
        return f"{_WEEKDAYS[parts[0][:3]]} *-*-* {_norm_time(parts[1])}"
    if len(parts) == 2 and parts[0] == "daily" and _is_time(parts[1]):
        return f"*-*-* {_norm_time(parts[1])}"
    if len(parts) == 1 and _is_time(parts[0]):
        return f"*-*-* {_norm_time(parts[0])}"
    return text  # assume it is already a valid OnCalendar expression


def wrapper_script(aios_bin: str, prompt: str, log_path: str) -> str:
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by `aios schedule` — runs an AIOS automation.\n"
        f"echo \"=== $(date) ===\" >> {shlex.quote(log_path)}\n"
        f"{shlex.quote(aios_bin)} ask {shlex.quote(prompt)} >> {shlex.quote(log_path)} 2>&1\n"
    )


def service_unit(name: str, wrapper_path: str) -> str:
    return (
        f"[Unit]\nDescription=AIOS automation: {name}\n\n"
        f"[Service]\nType=oneshot\nExecStart={wrapper_path}\n"
    )


def timer_unit(name: str, oncalendar: str) -> str:
    return (
        f"[Unit]\nDescription=AIOS automation timer: {name}\n\n"
        f"[Timer]\nOnCalendar={oncalendar}\nPersistent=true\n\n"
        f"[Install]\nWantedBy=timers.target\n"
    )


class Scheduler:
    def __init__(self, unit_dir: str, data_dir: str, aios_bin: str = "aios",
                 run_systemctl: bool = True):
        self.unit_dir = unit_dir
        self.auto_dir = os.path.join(data_dir, "automations")
        self.index_path = os.path.join(self.auto_dir, "index.json")
        self.aios_bin = aios_bin
        self.run_systemctl = run_systemctl and bool(shutil.which("systemctl"))

    # -- index helpers ----------------------------------------------------
    def _load_index(self) -> dict:
        if not os.path.exists(self.index_path):
            return {}
        try:
            with open(self.index_path, encoding="utf-8") as fh:
                return json.load(fh)
        except (OSError, ValueError):
            return {}

    def _save_index(self, index: dict) -> None:
        os.makedirs(self.auto_dir, exist_ok=True)
        with open(self.index_path, "w", encoding="utf-8") as fh:
            json.dump(index, fh, indent=2)

    def _systemctl(self, *args):
        if self.run_systemctl:
            subprocess.run(["systemctl", "--user", *args], check=False)

    # -- operations -------------------------------------------------------
    def add(self, name: str, when: str, prompt: str) -> dict:
        if not _NAME_RE.fullmatch(name):
            raise ScheduleError("name must be letters, digits, '-' or '_'")
        if not prompt.strip():
            raise ScheduleError("prompt is required")
        oncalendar = to_oncalendar(when)

        os.makedirs(self.unit_dir, exist_ok=True)
        os.makedirs(self.auto_dir, exist_ok=True)
        log_path = os.path.join(self.auto_dir, f"{name}.log")
        wrapper_path = os.path.join(self.auto_dir, f"{name}.sh")

        with open(wrapper_path, "w", encoding="utf-8") as fh:
            fh.write(wrapper_script(self.aios_bin, prompt, log_path))
        os.chmod(wrapper_path, 0o755)
        with open(os.path.join(self.unit_dir, f"aios-{name}.service"), "w") as fh:
            fh.write(service_unit(name, wrapper_path))
        with open(os.path.join(self.unit_dir, f"aios-{name}.timer"), "w") as fh:
            fh.write(timer_unit(name, oncalendar))

        record = {"name": name, "when": when, "oncalendar": oncalendar,
                  "prompt": prompt, "log": log_path, "created_at": time.time()}
        index = self._load_index()
        index[name] = record
        self._save_index(index)

        self._systemctl("daemon-reload")
        self._systemctl("enable", "--now", f"aios-{name}.timer")
        return record

    def list(self) -> list:
        return sorted(self._load_index().values(), key=lambda r: r.get("name", ""))

    def remove(self, name: str) -> bool:
        index = self._load_index()
        if name not in index:
            return False
        self._systemctl("disable", "--now", f"aios-{name}.timer")
        for path in (
            os.path.join(self.unit_dir, f"aios-{name}.service"),
            os.path.join(self.unit_dir, f"aios-{name}.timer"),
            os.path.join(self.auto_dir, f"{name}.sh"),
        ):
            try:
                os.remove(path)
            except OSError:
                pass
        del index[name]
        self._save_index(index)
        self._systemctl("daemon-reload")
        return True
